package:
  name: lw_hello
  version: 1.0.0

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - aiohttp

test:
  imports:
    - lw_hello

about:
  home: https://github.com/lkwilson/hello
  license: MIT
  summary: 'Says hello'
  description: 'Says hello'
  dev_url: https://github.com/lkwilson/hello
  doc_url: https://github.com/lkwilson/hello
  doc_source_url: https://github.com/lkwilson/hello

