package:
  name: hc
  version: 1.0.0

source:
  path: ..

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - aiohttp

test:
  imports:
    - hc

about:
  home: https://github.com/lkwilson/hc
  license: MIT
  summary: 'Library to control outlets'
  description: 'Library to control outlets'
  dev_url: https://github.com/lkwilson/hc
  doc_url: https://github.com/lkwilson/hc
  doc_source_url: https://github.com/lkwilson/hc

